### ISSUE TITLE
index not provided

### ISSUE THREAD

**Issue by stevenvachon** [yoshuawuyts/promise-each#2]
From [`bluebird.each` docs](https://github.com/petkaantonov/bluebird/blob/master/API.md#eachfunction-iterator---promise):

> Iterate over an array, or a promise of an array, which contains promises (or a mix of promises and values) with the given `iterator` function with the signature `(item, index, value)` where `item` is the resolved value of a respective promise in the input array. Iteration happens serially. If any promise in the input array is rejected the returned promise is rejected as well.

Particularly the **(item, index, value)** part.

I'm not sure what `value` is supposed to be, though.

**Comment by yoshuawuyts** [comment]
I'm not sure either about `value`; maybe they mean the context value (e.g. `this`) ? I think you're right about adding `index`, should be a minor change. PRs are welcome.

**Comment by stevenvachon** [comment]
Opened this: https://github.com/petkaantonov/bluebird/issues/790
